apiVersion: apps/v1
kind: Deployment
metadata:
  name: telephone-api-deployment
  namespace: default
  labels:
    app: telephone-api
spec:
  replicas: 2 # Puedes subirlo o bajarlo según cuántos pods quieras
  selector:
    matchLabels:
      app: telephone-api
  template:
    metadata:
      labels:
        app: telephone-api
    spec:
      # -----------------------------------

      containers:
      - name: telephone-api
        image: lutespatella/telephone-api:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # Cambia al puerto que use tu API (ej: 8080, 3000)
        
        # Buenas prácticas: Limitar recursos para que no sature el nodo
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "500Mi"
        
        # Variables de entorno (si tu API necesita conectarse a una BD u otro servicio)
        # AQUÍ INYECTAMOS LAS VARIABLES DESDE EL SECRET
        env:
        - name: DATABASE_URL
          value: postgresql://user:devpassword123@postgres:5432/telephone_db
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq:5672/%2F
        - name: OLLAMA_URL
          value: http://ollama:11434
        - name: OLLAMA_MODEL
          value: llama3.2:1b
        - name: DATABASE_USER           # El nombre de la variable que lee tu código (ej: Spring)
          valueFrom:
            secretKeyRef:
              name: credentials     # Nombre de tu objeto Secret
              key: POSTGRES_USER            # La clave dentro del Secret
              
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: POSTGRES_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: telephone-api-service
  namespace: default
spec:
  type: LoadBalancer # Usa NodePort o LoadBalancer si necesitas exponerlo directo al exterior sin Ingress
  selector:
    app: telephone-api
  ports:
    - protocol: TCP
      port: 80        # Puerto del servicio interno
      targetPort: 8080 # Puerto donde escucha el contenedor