apiVersion: apps/v1
kind: Deployment
metadata:
  name: telephone-llm-worker-deployment
  namespace: default
  labels:
    app: telephone-llm-worker
spec:
  replicas: 1 # Puedes subirlo o bajarlo según cuántos pods quieras
  selector:
    matchLabels:
      app: telephone-llm-worker
  template:
    metadata:
      labels:
        app: telephone-llm-worker
    spec:
      containers:
      - name: telephone-llm-worker
        image: lutespatella/telephone-llm_worker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: postgresql://user:devpassword123@postgres:5432/telephone_db
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq:5672/%2F
        - name: OLLAMA_URL
          value: http://ollama:11434
        - name: OLLAMA_MODEL
          value: llama3.2:1b
        - name: DATABASE_USER           # El nombre de la variable que lee tu código (ej: Spring)
          valueFrom:
            secretKeyRef:
              name: credentials     # Nombre de tu objeto Secret
              key: db-user             # La clave dentro del Secret
              
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: db-password