apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Al no especificar storageClassName, tu clúster usará la que tenga por defecto (ej: Cinder de OpenStack)

---
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "devpassword123"
        - name: POSTGRES_DB
          value: "telephone_db"
        volumeMounts:
        - name: postgres-volume
          mountPath: /root/.postgres

      volumes:
      - name: postgres-volume
        persistentVolumeClaim:
          claimName: postgres-storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres # <--- Este nombre exacto activará el DNS interno "postgres"
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres