apiVersion:  v1
kind:  Secret
metadata: 
  name:  credentials      # El nombre con el que lo vas a llamar desde la API
  namespace:  default
type:  Opaque                # "Opaque" es el tipo por defecto para secretos genéricos
stringData: 
  # Los valores DEBEN estar en Base64. 
  # echo -n "pass" | base64
  # "root" en Base64 es:  cm9vdA: : 
  # "mi_password_seguro" en Base64 es:  bWlfcGFzc3dvcmRfc2VndXJv
  # PostgreSQL Configuration
  db-user: telephone_user
  db-password: DistortionGameP1
  POSTGRES_USER:  telephone_user
  POSTGRES_PASSWORD: DistortionGameP1
  POSTGRES_DB: telephone_db

  # # RabbitMQ Configuration
  # RABBITMQ_DEFAULT_USER: telephone_admin
  # RABBITMQ_DEFAULT_PASS: MessageQueue_RB

  # # API Configuration
  # DATABASE_URL: postgresql://telephone_user:DistortionGameP1@postgres:5432/telephone_db
  # RABBITMQ_URL: amqp://telephone_admin:MessageQueue_RB@rabbitmq:5672//

  # # Ollama Configuration
  # OLLAMA_URL: http://ollama:11434
  # OLLAMA_MODEL: llama3.2:1b
  # OLLAMA_HOST: 0.0.0.0:11434

  # # API Runtime
  # API_HOST: 0.0.0.0
  # API_PORT: 8000
  # LOG_LEVEL: INFO

  # # Application Settings
  # DISTORTION_PROB: 0.25
  # BATCH_SIZE: 5
  # BATCH_TIMEOUT: float(os.getenv("LLM_BATCH_TIMEOUT", "20"))
