apiVersion: v1
kind: Secret
metadata:
  name: db-credentials      # El nombre con el que lo vas a llamar desde la API
  namespace: default
type: Opaque                # "Opaque" es el tipo por defecto para secretos genéricos
data:
  # Los valores DEBEN estar en Base64. 
  # echo -n "pass" | base64
  # "root" en Base64 es: cm9vdA==
  # "mi_password_seguro" en Base64 es: bWlfcGFzc3dvcmRfc2VndXJv
  db-user: cm9vdA==
  db-password: bWlfcGFzc3dvcmRfc2VndXJv