apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-keda-secret
  namespace: default
type: Opaque
stringData:
  # Host con el nombre de dominio calificado completo (FQDN) para KEDA
  host: amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/%2F

---
apiVersion: v1
kind: Secret
metadata: 
  name: credentials
  namespace: default
type: Opaque
stringData: 
  # Variables nativas consumidas por tu API y Workers de Python
  db-user: telephone_user
  db-password: DistortionGameP1
  POSTGRES_USER: telephone_user
  POSTGRES_PASSWORD: DistortionGameP1
  POSTGRES_DB: telephone_db
  JOBS_QUEUE: telephone.jobs
  RESULTS_QUEUE: telephone.results