from sqlalchemy import create_engine, Column, String, Integer, DateTime, Text, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime
import os

# Database configuration
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://user:password@localhost:5432/telephone_db"
)

engine = create_engine(DATABASE_URL, echo=False)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


class Job(Base):
    """
    Represents a telephone game job.
    
    Attributes:
        id: Unique job identifier
        phrase: Original phrase to be distorted
        num_workers: Number of workers to process this job
        status: Current status (pending, running, completed, failed)
        created_at: Timestamp of job creation
        distorted_phrases: Relationship to distorted phrase records
        guesses: Relationship to guess records
    """
    __tablename__ = "jobs"

    id = Column(String, primary_key=True)
    phrase = Column(Text, nullable=False)
    num_workers = Column(Integer, nullable=False)
    status = Column(String, default="pending")
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    distorted_phrases = relationship("DistortedPhrase", back_populates="job", cascade="all, delete-orphan")
    guesses = relationship("Guess", back_populates="job", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Job(id={self.id}, phrase={self.phrase[:50]}, num_workers={self.num_workers}, status={self.status})>"


class DistortedPhrase(Base):
    """
    Represents a distorted phrase generated by a worker.
    
    Attributes:
        id: Unique identifier (auto-generated)
        job_id: Foreign key referencing the job
        worker_id: Identifier of the worker that generated this distortion
        distorted_phrase: The distorted phrase text
        job: Relationship to the Job
    """
    __tablename__ = "distorted_phrases"

    id = Column(Integer, primary_key=True, autoincrement=True)
    job_id = Column(String, ForeignKey("jobs.id"), nullable=False)
    worker_id = Column(Integer, nullable=False)
    distorted_phrase = Column(Text, nullable=False)

    # Relationship
    job = relationship("Job", back_populates="distorted_phrases")

    def __repr__(self):
        return f"<DistortedPhrase(job_id={self.job_id}, worker_id={self.worker_id}, phrase={self.distorted_phrase[:50]})>"


class Guess(Base):
    """
    Represents a guess made by the LLM worker (Ollama).
    
    Attributes:
        id: Unique identifier (auto-generated)
        job_id: Foreign key referencing the job
        batch_num: Batch number for incremental guessing
        guess: The reconstructed phrase guess
        ollama_response: Full response from Ollama model
        job: Relationship to the Job
    """
    __tablename__ = "guesses"

    id = Column(Integer, primary_key=True, autoincrement=True)
    job_id = Column(String, ForeignKey("jobs.id"), nullable=False)
    batch_num = Column(Integer, nullable=False)
    guess = Column(Text, nullable=False)
    ollama_response = Column(Text, nullable=True)

    # Relationship
    job = relationship("Job", back_populates="guesses")

    def __repr__(self):
        return f"<Guess(job_id={self.job_id}, batch_num={self.batch_num}, guess={self.guess[:50]})>"


def init_db():
    """Initialize all database tables."""
    Base.metadata.create_all(bind=engine)


def get_db():
    """Get a database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
