apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-storage
  namespace: telephone-distortion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # Al no especificar storageClassName, tu clúster usará la que tenga por defecto (ej: Cinder de OpenStack)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
  namespace: telephone-distortion
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      # --- CLAVE PARA TU NODO ESPECIAL ---
      tolerations:
      - key: "reservado"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/hostname: nocompila-special-node

      containers:
      - name: ollama
        image: ollama/ollama:0.3.14
        ports:
        - containerPort: 11434
          name: api
        env:
        - name: OLLAMA_MODELS
          value: "qwen2.5:0.5b"
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "3Gi"

        # Montamos el volumen persistente en la ruta donde Ollama guarda los modelos
        volumeMounts:
        - name: ollama-volume
          mountPath: /root/.ollama

      volumes:
      - name: ollama-volume
        persistentVolumeClaim:
          claimName: ollama-storage

---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: telephone-distortion
spec:
  type: ClusterIP # Cambia a ClusterIP para que tu API lo consuma internamente usando http://ollama-service:11434
  ports:
    - port: 11434
      targetPort: 11434
  selector:
    app: ollama
