apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-storage
  namespace: telephone-distortion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: telephone-distortion
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:4.3-alpine
        ports:
        - containerPort: 5672
          name: amqp
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: RABBITMQ_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: credentials
              key: RABBITMQ_PASS
        volumeMounts:
        - name: rabbitmq-volume
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-volume
        persistentVolumeClaim:
          claimName: rabbitmq-storage

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: telephone-distortion
spec:
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  selector:
    app: rabbitmq