apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: telephone-worker-scaler-job
  namespace: telephone-distortion
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3

  scalingStrategy:
    strategy: "accurate"

  jobTargetRef:
    parallelism: 5
    completions: 5
    activeDeadlineSeconds: 120
    ttlSecondsAfterFinished: 30

    template:
      metadata:
        labels:
          app: telephone-worker-job
      spec:
        restartPolicy: Never
        containers:
        - name: telephone-worker-job  # Added "-" and fixed indentation
          image: juanignaciomassacesi/telephone-worker:v1
          imagePullPolicy: Always
          env:
          - name: DATABASE_URL        # Added "-" and fixed indentation
            valueFrom:
              secretKeyRef:
                name: credentials
                key: DATABASE_URL
          - name: RABBITMQ_URL        # Added "-" and fixed indentation
            valueFrom:
              secretKeyRef:
                name: credentials
                key: RABBITMQ_URL
          - name: OLLAMA_URL          # Added "-" and fixed indentation
            value: http://ollama.telephone-distortion.svc.cluster.local:11434/
          - name: OLLAMA_MODEL        # Added "-" and fixed indentation
            value: llama3.2:1b

  maxReplicaCount: 20

  triggers:
  - type: rabbitmq              # Added "-" and fixed indentation
    metadata:
      protocol: amqp
      queueName: telephone.jobs
      mode: QueueLength
      value: "100"
    authenticationRef:
      name: rabbitmq-job-auth

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-job-auth
  namespace: telephone-distortion
spec:
  secretTargetRef:
  - parameter: host            # Added "-" and fixed indentation
    name: rabbitmq-keda-secret
    key: host