apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: telephone-worker-scaler-job
  namespace: telephone-distortion
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 3

  scalingStrategy:
    strategy: "accurate"

  jobTargetRef:
    parallelism: 5
    completions: 5
    activeDeadlineSeconds: 120
    ttlSecondsAfterFinished: 30

    template:
      metadata:
        labels:
          app: telephone-worker-job
      spec:
        restartPolicy: Never
        containers:
        - name: telephone-worker-job  
          image: lutespatella/telephone-worker:v4
          imagePullPolicy: Always
          env:
          - name: DATABASE_URL        
            valueFrom:
              secretKeyRef:
                name: credentials
                key: DATABASE_URL
          - name: RABBITMQ_URL        
            valueFrom:
              secretKeyRef:
                name: credentials
                key: RABBITMQ_URL
          - name: OLLAMA_URL          
            value: http://ollama.telephone-distortion.svc.cluster.local:11434/
          - name: OLLAMA_MODEL        
            value: qwen2.5:0.5b

  maxReplicaCount: 5

  triggers:
  - type: rabbitmq              
    metadata:
      protocol: amqp
      queueName: telephone.jobs
      mode: QueueLength
      value: "200"
    authenticationRef:
      name: rabbitmq-job-auth

---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-job-auth
  namespace: telephone-distortion
spec:
  secretTargetRef:
  - parameter: host            
    name: rabbitmq-keda-secret
    key: host