apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-keda-secret
  namespace: telephone-distortion
type: Opaque
stringData:
  host: amqp://telephone_admin:MessageQueue_RB@rabbitmq.telephone-distortion.svc.cluster.local:5672/%2F

---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: telephone-distortion
type: Opaque
stringData:
  POSTGRES_USER: telephone_user
  POSTGRES_PASSWORD: DistortionGameP1
  POSTGRES_DB: telephone_db
  DATABASE_URL: postgresql://telephone_user:DistortionGameP1@postgres.telephone-distortion.svc.cluster.local:5432/telephone_db
  RABBITMQ_URL: amqp://telephone_admin:MessageQueue_RB@rabbitmq.telephone-distortion.svc.cluster.local:5672/%2F
  RABBITMQ_USER: telephone_admin
  RABBITMQ_PASS: MessageQueue_RB
  JOBS_QUEUE: telephone.jobs
  RESULTS_QUEUE: telephone.results