apiVersion: apps/v1
kind: Deployment
metadata:
  name: telephone-worker-deployment
  namespace: telephone-distortion
  labels:
    app: telephone-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telephone-worker
  template:
    metadata:
      labels:
        app: telephone-worker
    spec:
      containers:
      - name: telephone-worker
        image: juanignaciomassacesi/telephone-worker:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: credentials
              key: DATABASE_URL
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: credentials
              key: RABBITMQ_URL
        - name: OLLAMA_URL
          value: http://ollama.telephone-distortion.svc.cluster.local:11434
        - name: OLLAMA_MODEL
          value: llama3.2:1b
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: credentials
              key: POSTGRES_DB